# <center>Практическое задание к уроку 2.  
## Часть 1.

In [9]:
import numpy as np
import numpy.linalg

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.  
   
 ---

а) Поскольку число столбцов матрицы $A$(2) не равно числу строк матрицы $B$ (4), $\Rightarrow A\cdot B\text{ не определено}$, а поскольку число столбцов матрицы $B$ (2), так же не равно числу строк матрицы $A$ (4), $\Rightarrow B\cdot A\text{ так же, не определено}$  

---
б) $A\cdot B$ определено, полученная матрица имеет размер $2\times 3$, $B\cdot A\text{ не определено}$  

---  
в) $A\cdot B$ определено, полученная матрица имеет размер $8\times 8$, $B\cdot A$ определено, полученная матрица имеет размер $3\times 3$  

---  
г) $A\cdot B$ и $B\cdot A$ определены и полученные матрицы имеют размер $4\times 4$.  

---

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$.

$A+B=\begin{pmatrix}1+4 & -2+(-1)\\3+0 & 0+5\end{pmatrix}=\begin{pmatrix}5 & -3\\3 & 5\end{pmatrix}$

In [43]:
A=np.array([[1,-2],[3,0]])
B=np.array([[4,-1],[0,5]])
C=np.arange(4).reshape(2,2)
for i in range(len(A)):
    for j in range(len(A[i])):
        C[i][j]=A[i][j]+B[i][j]
C

array([[ 5, -3],
       [ 3,  5]])

Проверим с numpy:  

In [15]:
A+B

array([[ 5, -3],
       [ 3,  5]])

---  
$A\cdot B=\begin{pmatrix}1 & -2\\3 & 0\end{pmatrix}\cdot \begin{pmatrix}4 & -1\\0 & 5\end{pmatrix}=\begin{pmatrix}1\cdot 4+(-2)\cdot 0 & 1\cdot -1+(-2)\cdot 5\\3\cdot 4+0\cdot 0 & 3\cdot -1 +0\cdot 5\end{pmatrix}=\begin{pmatrix}4 & -11\\12 & -3\end{pmatrix}$  

---
$B\cdot A=\begin{pmatrix}4 & -1\\0 & 5\end{pmatrix}\cdot\begin{pmatrix}1 & -2\\3 & 0\end{pmatrix} =\begin{pmatrix}4\cdot 1+(-1)\cdot 3 & 4\cdot -2+(-1)\cdot 0\\0\cdot 1+5\cdot 3 & 0\cdot -2 +5\cdot 0\end{pmatrix}=\begin{pmatrix}1 & -8\\15 & 0\end{pmatrix}$  

---

Проверим с numpy: 

In [14]:
A@B

array([[  4, -11],
       [ 12,  -3]])

In [15]:
B@A

array([[ 1, -8],
       [15,  0]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}$.

---  
$3A-2B+4C=3\cdot \begin{pmatrix}1 & 7\\3 & -6\end{pmatrix}-2\cdot \begin{pmatrix}0 & 5\\2 & -1\end{pmatrix}+4\cdot \begin{pmatrix}2 & -4\\ 1 & 1\end{pmatrix}=\begin{pmatrix}1\cdot 3 & 7\cdot 3\\3\cdot 3 & -6\cdot 3\end{pmatrix}-\begin{pmatrix}0\cdot 2 & 5\cdot 2\\2\cdot 2 & -1\cdot 2\end{pmatrix}+\begin{pmatrix}2\cdot 4 & -4\cdot 4\\ 1\cdot 4 & 1\cdot 4\end{pmatrix}=\begin{pmatrix}3-0+8 & 21-10-16\\9-4+4 & -18+2+4\end{pmatrix}=\begin{pmatrix}11 & -5\\9 & -12\end{pmatrix}$  

---

Проверим с numpy:

In [16]:
a=np.array([[1,7],[3,-6]])
b=np.array([[0,5],[2,-1]])
c=np.array([[2,-4],[1,1]])
3*a-2*b+4*c

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

---  
$A^T=\begin{pmatrix}4 & 5 & 2\\1 &-2 & 3\end{pmatrix}$  
$AA^T=\begin{pmatrix}4 & 1\\ 5 & -2\\ 2 & 3\end{pmatrix}\cdot \begin{pmatrix}4 & 5 & 2\\1 &-2 & 3\end{pmatrix}=\begin{pmatrix}4\cdot 4+1\cdot 1 & 4\cdot 5+1\cdot -2 & 4\cdot 2+1\cdot 3\\5\cdot 4+(-2)\cdot 1 & 5\cdot 5+(-2)\cdot -2 & 5\cdot 2+(-2)\cdot 3\\2\cdot 4+3\cdot 1 & 2\cdot 5+3\cdot -2 & 2\cdot 2+3\cdot 3\end{pmatrix}=\begin{pmatrix}17 & 18 & 11\\18 & 29 & 4\\11 & 4 & 13\end{pmatrix}$

$A^{T}A=\begin{pmatrix}4 & 5 & 2\\1 &-2 & 3\end{pmatrix}\cdot \begin{pmatrix}4 & 1\\ 5 & -2\\ 2 & 3\end{pmatrix}=\begin{pmatrix}4\cdot 4 + 5\cdot 5+2\cdot 2 & 4\cdot 1 + 5\cdot -2+2\cdot 3\\1\cdot 4 + (-2)\cdot 5+3\cdot 2 & 1\cdot 1 + (-2)\cdot -2+3\cdot 3\end{pmatrix}=\begin{pmatrix}45 & 0\\0 & 14\end{pmatrix}$

In [32]:
# Функция возвращает транспонированную матрицу
def trans_matrix(matrix):
    trans=np.empty(shape=[matrix.shape[1],matrix.shape[0]])
    for i in range(trans.shape[0]):
        for j in range(trans.shape[1]):
            trans[i][j]=matrix[j][i]
    return trans

Проверим с numpy:

In [33]:
A=np.array([[4,1],[5,-2],[2,3]])
trans_matrix(A)

array([[ 4.,  5.,  2.],
       [ 1., -2.,  3.]])

In [34]:
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [35]:
A@trans_matrix(A)

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

In [36]:
A@A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [37]:
trans_matrix(A)@A

array([[45.,  0.],
       [ 0., 14.]])

In [38]:
A.T@A

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [215]:
def multiplicate_matrix(left,right):
    try: 
        left.shape[1]==right.shape[0]
        result=[]
        temp=[]
        s=0
        for i in range(left.shape[0]):
            for j in range(right.shape[1]):
                for k in range(right.shape[0]):
                    s+=left[i][k]*right[k][j]
                temp.append(s)
                s=0
            result.append(temp)
            temp=[]
        return np.array(result)
    except Exception:
        print('Произведение матриц таких размеров не определено!')

In [216]:
A=np.array([[1,-2],[3,0],[4,1],[6,9]])
B=np.array([[4,-1,3,2],[0,5,2,-5]])

In [217]:
A.dot(B)

array([[  4, -11,  -1,  12],
       [ 12,  -3,   9,   6],
       [ 16,   1,  14,   3],
       [ 24,  39,  36, -33]])

In [218]:
multiplicate_matrix(A,B)

array([[  4, -11,  -1,  12],
       [ 12,  -3,   9,   6],
       [ 16,   1,  14,   3],
       [ 24,  39,  36, -33]])

In [219]:
B.dot(A)

array([[ 25,  13],
       [ -7, -43]])

In [220]:
multiplicate_matrix(B,A)

array([[ 25,  13],
       [ -7, -43]])

## Часть 2.

__1.__ Вычислить определитель:

   a)

$\begin{pmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{pmatrix}$;

   б)
    
$\begin{pmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{pmatrix}$;
    
   в)

$\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix}$.

---  
а) Для матрицы порядка 2:  
$A=\begin{pmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{pmatrix}$,  
определитель вычисляется как:  
$detA=a_{11}a_{22} - a_{12}a_{21}$.  
Тогда:  
$A=\begin{pmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{pmatrix}$  
$detA=\sin x \cdot sin x - (-\cos x)\cdot\cos x=\sin^2 x + \cos^2 x=1$

Проверка:

In [10]:
for x in range(0,11,2):
    A=np.array([[np.sin(x), -np.cos(x)],[np.cos(x), np.sin(x)]])
    print(x, round(np.linalg.det(A)))

0 1
2 1
4 1
6 1
8 1
10 1


б)  
$B=\begin{pmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{pmatrix}$   
Воспользуемся свойством определителя матрицы треугольного вида:  
**Определитель матрицы треугольного вида равен произведению элементов, стоящих на ее главной диагонали**  
$detB=4\cdot 5\cdot 9=180$

Проверка:  

In [205]:
B=np.array([[4,2,3], [0,5,1],[0,0,9]])  
np.linalg.det(B)

180.0

в)  Разложим по элементам первой строки:  
$C=\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix}$  
$detC=1\cdot\begin{pmatrix}5 & 6\\8 & 9\end{pmatrix}-2\cdot\begin{pmatrix}4 & 6\\7 & 9\end{pmatrix}+3\cdot\begin{pmatrix}4 & 5\\7 & 8\end{pmatrix}=1\cdot (5\cdot 9-6\cdot 8)-2\cdot (4\cdot 9-6\cdot 7)+3\cdot (4\cdot 8-5\cdot 7)=0$

Проверка:  

In [153]:
C=np.array([[1,2,3], [4,5,6],[7,8,9]])  
round(np.linalg.det(C),1)

-0.0

**Функция для вычисления определителя**

In [231]:
def my_det(matrix):
    '''
    Функция вычисляет определитель матрицы(с порядком не превышающим 5), принимает в качестве аргумента двумерный массив numpy
    '''
    assert len(matrix)==len(matrix[0]), 'Матрица должна быть квадратной!'
    if len(matrix)==2:
        return matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]
    else:
        mults=[((-1)**i)*el for i,el in enumerate(matrix[0])]
        minor=[]
        total=[]
        for i in range(len(mults)):
            for row in matrix[1:]:
                minor.append(np.delete(row,i))
            total.append(minor)
            minor=[]
        return sum([mult*my_det(element) for mult, element in zip(mults,total)])

                    

Проверка: 

In [236]:
B=np.array([[4,2,3], [0,5,1],[0,0,9]])
my_det(B)

180

In [237]:
np.linalg.det(B)

180.0

In [238]:
D= np.array([[-1, -4, 0, -2], [0, 1, 5, 4], [3, 1, 1, 0], [-1, 0, 2, 2]])
my_det(D)

-12

In [239]:
np.linalg.det(D)

-11.999999999999995

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.  
   
---

a) Используем следующее свойство определителя:  

**Для двух квадратных матриц одинакового размера**  

$det(AB)=detA\cdot detB$.  

Следовательно:  

$det(A^2)=det(A\cdot A)=det(A)\cdot det(A)=4\cdot 4=16$  

---

б) Используем следующее свойство определителя:  

**Определитель транспонированной матрицы равен определителю исходной:**  

$detA^{T}=detA$.  

Следовательно:  

$det(A^T)=4$  

---

в) Из свойства определителя:  

**Умножение строки или столбца матрицы на число  𝜆  приведет к умножению определителя матрицы на то же число.**  

Следует, что $det(2A)=2^{n}\cdot det(A)=2^{n}\cdot 4$, где $n$ - порядок матрицы $A$.  

*Пояснение: если поочередно умножать каждую строку матрицы $n\times n$, определитель которой равен $a$ на некоторое число $\lambda$, то определитель каждой матрицы, полученной в результате такого умножения будет превышать определитель предыдущей матрицы в $\lambda$ раз. Поскольку нам потребуется $n$ таких операций построчного умножения, то определитель последней матрицы будет превышать определитель начальной матрицы в $\lambda^n$ раз.*  

__3.__  Доказать, что матрица

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
   
вырожденная.

Поскольку мы можем представить вторую строку данной матрицы $(4, -14, 6)$ через первую её строку $(-2, 7, -3)$ как  

$(4, -14, 6)=-2\cdot (-2, 7, -3)$, т.е. две строки (столбца) матрицы линейно зависимы, а значит её определитель равен $0$, т.е.  

такая матрица, согласно определению, является **вырожденной**.  

Проверим:  

In [25]:
arr=np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(arr)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$;

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$.

---
a)  

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$

Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:  

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$  

Из первой строки вычтем вторуюб и поменяем строки местами:  

$\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}$  

Ранг матрицы равен $2$  

Проверим:  

In [27]:
arr=([[1,2,3],[1,1,1],[2,3,4]])
np.linalg.matrix_rank(arr)

2

---  
б)  

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$  

Третья строка является суммой первой и второй строки, отбрасываем:  

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$  

Вычтем вторую строку из первой:  

$\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$  

Удалим второй столбец, который можно выразить через первый: 

$\begin{pmatrix}
0 & 0 & -1\\ 
0 & 2 & 2\\ 
2 & 5 & 6
\end{pmatrix}$  

Поменяем местами первую и третью строки:  

$\begin{pmatrix}
2 & 5 & 6\\ 
0 & 2 & 2\\ 
0 & 0 & -1
\end{pmatrix}$  

Ранг матрицы равен $3$  

Проверим:

In [29]:
arr=([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
np.linalg.matrix_rank(arr)

3